title: "The Secret Archive of aapsemiordoenus | Cybersecurity & Beyond: Paranoia Mind Hub -> I Love Genshin Impact !!! ←"
description: "ㅇㅅㅇ"
author_name: "aapsemiordoenus"
url: "https://aapsemiordoenus.github.io" # 본인 깃허브 주소로 변경
baseurl: ""

# 네비게이션 설정
navigation:
  - title: "Home"
    url: "/"
  - title: "Archive"
    url: "/archive"

# 마크다운 및 빌드 설정
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"